// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/points.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PointsService_LoginPoints_FullMethodName        = "/points.PointsService/LoginPoints"
	PointsService_GetUserPoints_FullMethodName      = "/points.PointsService/GetUserPoints"
	PointsService_GetUserArticle_FullMethodName     = "/points.PointsService/GetUserArticle"
	PointsService_AddArticleExposure_FullMethodName = "/points.PointsService/AddArticleExposure"
)

// PointsServiceClient is the client API for PointsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PointsServiceClient interface {
	LoginPoints(ctx context.Context, in *LoginPointsReq, opts ...grpc.CallOption) (*LoginPointsResp, error)
	GetUserPoints(ctx context.Context, in *GetUserPointsReq, opts ...grpc.CallOption) (*GetUserPointsResp, error)
	GetUserArticle(ctx context.Context, in *GetUserArticleReq, opts ...grpc.CallOption) (*GetUserArticleResp, error)
	AddArticleExposure(ctx context.Context, in *AddArticleExposureReq, opts ...grpc.CallOption) (*AddArticleExposureResp, error)
}

type pointsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPointsServiceClient(cc grpc.ClientConnInterface) PointsServiceClient {
	return &pointsServiceClient{cc}
}

func (c *pointsServiceClient) LoginPoints(ctx context.Context, in *LoginPointsReq, opts ...grpc.CallOption) (*LoginPointsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginPointsResp)
	err := c.cc.Invoke(ctx, PointsService_LoginPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsServiceClient) GetUserPoints(ctx context.Context, in *GetUserPointsReq, opts ...grpc.CallOption) (*GetUserPointsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPointsResp)
	err := c.cc.Invoke(ctx, PointsService_GetUserPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsServiceClient) GetUserArticle(ctx context.Context, in *GetUserArticleReq, opts ...grpc.CallOption) (*GetUserArticleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserArticleResp)
	err := c.cc.Invoke(ctx, PointsService_GetUserArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsServiceClient) AddArticleExposure(ctx context.Context, in *AddArticleExposureReq, opts ...grpc.CallOption) (*AddArticleExposureResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddArticleExposureResp)
	err := c.cc.Invoke(ctx, PointsService_AddArticleExposure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointsServiceServer is the server API for PointsService service.
// All implementations must embed UnimplementedPointsServiceServer
// for forward compatibility.
type PointsServiceServer interface {
	LoginPoints(context.Context, *LoginPointsReq) (*LoginPointsResp, error)
	GetUserPoints(context.Context, *GetUserPointsReq) (*GetUserPointsResp, error)
	GetUserArticle(context.Context, *GetUserArticleReq) (*GetUserArticleResp, error)
	AddArticleExposure(context.Context, *AddArticleExposureReq) (*AddArticleExposureResp, error)
	mustEmbedUnimplementedPointsServiceServer()
}

// UnimplementedPointsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPointsServiceServer struct{}

func (UnimplementedPointsServiceServer) LoginPoints(context.Context, *LoginPointsReq) (*LoginPointsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginPoints not implemented")
}
func (UnimplementedPointsServiceServer) GetUserPoints(context.Context, *GetUserPointsReq) (*GetUserPointsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPoints not implemented")
}
func (UnimplementedPointsServiceServer) GetUserArticle(context.Context, *GetUserArticleReq) (*GetUserArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserArticle not implemented")
}
func (UnimplementedPointsServiceServer) AddArticleExposure(context.Context, *AddArticleExposureReq) (*AddArticleExposureResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddArticleExposure not implemented")
}
func (UnimplementedPointsServiceServer) mustEmbedUnimplementedPointsServiceServer() {}
func (UnimplementedPointsServiceServer) testEmbeddedByValue()                       {}

// UnsafePointsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointsServiceServer will
// result in compilation errors.
type UnsafePointsServiceServer interface {
	mustEmbedUnimplementedPointsServiceServer()
}

func RegisterPointsServiceServer(s grpc.ServiceRegistrar, srv PointsServiceServer) {
	// If the following call pancis, it indicates UnimplementedPointsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PointsService_ServiceDesc, srv)
}

func _PointsService_LoginPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServiceServer).LoginPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointsService_LoginPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServiceServer).LoginPoints(ctx, req.(*LoginPointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointsService_GetUserPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPointsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServiceServer).GetUserPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointsService_GetUserPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServiceServer).GetUserPoints(ctx, req.(*GetUserPointsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointsService_GetUserArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServiceServer).GetUserArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointsService_GetUserArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServiceServer).GetUserArticle(ctx, req.(*GetUserArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointsService_AddArticleExposure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddArticleExposureReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServiceServer).AddArticleExposure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointsService_AddArticleExposure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServiceServer).AddArticleExposure(ctx, req.(*AddArticleExposureReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PointsService_ServiceDesc is the grpc.ServiceDesc for PointsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "points.PointsService",
	HandlerType: (*PointsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginPoints",
			Handler:    _PointsService_LoginPoints_Handler,
		},
		{
			MethodName: "GetUserPoints",
			Handler:    _PointsService_GetUserPoints_Handler,
		},
		{
			MethodName: "GetUserArticle",
			Handler:    _PointsService_GetUserArticle_Handler,
		},
		{
			MethodName: "AddArticleExposure",
			Handler:    _PointsService_AddArticleExposure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/points.proto",
}
