// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: points.proto

package server

import (
	"context"

	"sea-try-go/service/points/rpc/internal/logic"
	"sea-try-go/service/points/rpc/internal/svc"
	"sea-try-go/service/points/rpc/pb"
)

type PointsServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedPointsServiceServer
}

func NewPointsServiceServer(svcCtx *svc.ServiceContext) *PointsServiceServer {
	return &PointsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PointsServiceServer) LoginPoints(ctx context.Context, in *__.LoginPointsReq) (*__.LoginPointsResp, error) {
	l := logic.NewLoginPointsLogic(ctx, s.svcCtx)
	return l.LoginPoints(in)
}

func (s *PointsServiceServer) GetUserPoints(ctx context.Context, in *__.GetUserPointsReq) (*__.GetUserPointsResp, error) {
	l := logic.NewGetUserPointsLogic(ctx, s.svcCtx)
	return l.GetUserPoints(in)
}

func (s *PointsServiceServer) GetUserArticle(ctx context.Context, in *__.GetUserArticleReq) (*__.GetUserArticleResp, error) {
	l := logic.NewGetUserArticleLogic(ctx, s.svcCtx)
	return l.GetUserArticle(in)
}

func (s *PointsServiceServer) AddArticleExposure(ctx context.Context, in *__.AddArticleExposureReq) (*__.AddArticleExposureResp, error) {
	l := logic.NewAddArticleExposureLogic(ctx, s.svcCtx)
	return l.AddArticleExposure(in)
}
